# Generated by Django 4.2.17 on 2025-01-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='body',
            field=models.TextField(default='text'),
            preserve_default=False,
        ),
    ]
